# -*- coding: utf-8 -*-
"""Salinan Coba Coba Gaje.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kTuJx4m5NxXdoAVY7cWdbf31j6Cgq002
"""

# CELL 1: INSTALASI DAN IMPORT LIBRARY
!pip install PyWavelets -q

import cv2
import numpy as np
import pywt
import scipy.fftpack as fftpack
import hashlib
import time
import json
import os
import matplotlib.pyplot as plt
import matplotlib.patches as patches
from google.colab import files
import glob
import io

print("[+] Cell 1 Sukses. Semua library telah siap.")

# =========================================================================
# CELL 2: ASYMMETRICAL HASHING MACHINE (Pake YCbCr) — WARNA ABSOLUT + HH MASKED TEXT DETECTION
# =========================================================================
import cv2
import numpy as np
import pywt
import scipy.fftpack as fftpack

def preprocess_image(img):
    img_resized = cv2.resize(img, (512, 512))
    if len(img_resized.shape) == 3:
        return cv2.cvtColor(img_resized, cv2.COLOR_BGR2YCrCb)
    return img_resized

def extract_block_hash(block_ycbcr):
    y, cr, cb = cv2.split(block_ycbcr) if len(block_ycbcr.shape) == 3 else [block_ycbcr]*3

    coeffs = pywt.dwt2(y, 'haar')
    LL, _ = coeffs
    dct_y = fftpack.dct(fftpack.dct(LL.T, norm='ortho').T, norm='ortho')

    dct_low = dct_y[0:16, 0:16]
    phash_struktur = "".join(['1' if val > np.mean(dct_low) else '0' for val in dct_low.flatten()])
    dct_mid = dct_y[16:32, 16:32]
    phash_struktur += "".join(['1' if val > np.mean(dct_mid) else '0' for val in dct_mid.flatten()])

    h, w = cr.shape
    half_h, half_w = h // 2, w // 2
    color_stats = []
    for (r0, r1) in [(0, half_h), (half_h, h)]:
        for (c0, c1) in [(0, half_w), (half_w, w)]:
            color_stats.append(float(np.mean(cr[r0:r1, c0:c1])))
            color_stats.append(float(np.mean(cb[r0:r1, c0:c1])))

    return phash_struktur, color_stats

def generate_grid_hashes(img_ycbcr, grid_size=4):
    h, w = img_ycbcr.shape[:2]
    step_h, step_w = h // grid_size, w // grid_size
    grid_hashes, grid_colors = [], []
    for i in range(grid_size):
        row_hashes, row_colors = [], []
        for j in range(grid_size):
            block = img_ycbcr[i*step_h:(i+1)*step_h, j*step_w:(j+1)*step_w]
            h_struct, c_stats = extract_block_hash(block)
            row_hashes.append(h_struct)
            row_colors.append(c_stats)
        grid_hashes.append(row_hashes)
        grid_colors.append(row_colors)
    return grid_hashes, grid_colors

def calculate_hamming_distance(hash1, hash2):
    return sum(c1 != c2 for c1, c2 in zip(hash1, hash2))

def build_text_mask(img_ycbcr, canny_low=50, canny_high=150, dilate_size=3):
    """
    Mask biner: 1 = area terindikasi teks/tepi tajam, 0 = area datar/normal.
    Edge tipis hasil Canny di-dilate supaya stroke huruf yang berdekatan tersambung
    jadi satu blob "teks", bukan cuma garis tipis individual.
    """
    y = img_ycbcr[:, :, 0].astype(np.uint8)
    edges = cv2.Canny(y, canny_low, canny_high)
    kernel = np.ones((dilate_size, dilate_size), np.uint8)
    text_mask = cv2.dilate(edges, kernel, iterations=1)
    return (text_mask > 0).astype(np.float32)  # 1.0 = text-like, 0.0 = flat

def compute_hh_subband(img_ycbcr):
    """Subband HH (detail diagonal) dari DWT haar channel Y — energi/ketajaman lokal."""
    y = img_ycbcr[:, :, 0].astype(np.float64)
    _, (_, _, HH) = pywt.dwt2(y, 'haar')
    return HH

def compute_masked_block_stats(HH_matrix, inverse_mask, grid_size=4, min_valid_fraction=0.1):
    """
    Untuk tiap blok grid, hitung variansi/energi HH HANYA pada piksel non-teks
    (diizinkan oleh inverse_mask), MENGABAIKAN area tepi/tulisan — logika persis
    dari idemu, cuma di-loop per blok (bukan cuma cari 1 max_variance global)
    supaya bisa nge-flag blok mana yang berubah.

    Return: (valid_pixels_map, variance_map) — list of lists (grid_size x grid_size)
      valid_pixels_map[i][j] : jumlah piksel "bersih" (non-teks) di blok itu
      variance_map[i][j]     : rata-rata energi HH di piksel non-teks
                                (-1 kalau blok terlalu didominasi teks utk dihitung andal)
    """
    h, w = HH_matrix.shape
    step_h, step_w = h // grid_size, w // grid_size
    total_pixel_blok = step_h * step_w
    min_valid_pixels = min_valid_fraction * total_pixel_blok

    # inverse_mask dihitung dari citra 512x512, HH_matrix separuhnya (256x256) -> samakan skala
    mask_resized = cv2.resize(inverse_mask, (w, h), interpolation=cv2.INTER_AREA)

    valid_pixels_map, variance_map = [], []
    for i in range(grid_size):
        row_vp, row_var = [], []
        for j in range(grid_size):
            patch = HH_matrix[i*step_h:(i+1)*step_h, j*step_w:(j+1)*step_w]
            mask_patch = mask_resized[i*step_h:(i+1)*step_h, j*step_w:(j+1)*step_w]
            valid_pixels = float(np.sum(mask_patch))
            row_vp.append(valid_pixels)
            if valid_pixels > min_valid_pixels:
                row_var.append(float(np.sum(np.abs(patch) * mask_patch) / valid_pixels))
            else:
                row_var.append(-1.0)
        valid_pixels_map.append(row_vp)
        variance_map.append(row_var)
    return valid_pixels_map, variance_map

print("[+] Cell 2 Siap — warna absolut + deteksi teks via HH subband masked (Canny mask) siap dipakai.")

# =========================================================================
# CELL 4: SECURE BLOCKCHAIN & BK-TREE SEARCH ENGINE (FINAL MASTER) — + grid_colors + HH text mask stats
# =========================================================================
import hashlib
import json
import time
import os

def calculate_hamming_distance(h1, h2):
    if len(h1) != len(h2):
        return float('inf')
    return sum(el1 != el2 for el1, el2 in zip(h1, h2))

class BKTreeNode:
    def __init__(self, item):
        self.item = item
        self.children = {}

class BKTree:
    def __init__(self, distance_func=calculate_hamming_distance):
        self.root = None
        self.distance_func = distance_func

    def _get_representative_hash(self, item):
        grid_hashes = item[1] if isinstance(item, (tuple, list)) and len(item) > 1 else item
        if isinstance(grid_hashes, list):
            if len(grid_hashes) > 0 and isinstance(grid_hashes[0], list):
                return "".join([str(h) for row in grid_hashes for h in row])
            return "".join([str(h) for h in grid_hashes])
        return str(grid_hashes)

    def insert(self, item):
        if self.root is None:
            self.root = BKTreeNode(item)
            return
        node = self.root
        item_hash = self._get_representative_hash(item)
        while True:
            curr_hash = self._get_representative_hash(node.item)
            dist = self.distance_func(item_hash, curr_hash)
            if dist in node.children:
                node = node.children[dist]
            else:
                node.children[dist] = BKTreeNode(item)
                break

    def search_best_match(self, target_grid_hashes):
        if self.root is None:
            return None, float('inf')
        target_hash = self._get_representative_hash(target_grid_hashes)
        best_item = None
        min_dist = float('inf')
        candidates = [self.root]
        while candidates:
            node = candidates.pop()
            curr_hash = self._get_representative_hash(node.item)
            dist = self.distance_func(target_hash, curr_hash)
            if dist < min_dist:
                min_dist = dist
                best_item = node.item
            for d, child in node.children.items():
                if abs(d - dist) <= min_dist:
                    candidates.append(child)
        return best_item, min_dist

class Block:
    def __init__(self, index, timestamp, grid_hashes, metadata, previous_hash,
                 grid_colors=None, text_valid_pixels_map=None, text_variance_map=None):
        self.index = index
        self.timestamp = timestamp
        self.grid_hashes = grid_hashes
        self.grid_colors = grid_colors
        self.text_valid_pixels_map = text_valid_pixels_map  # BARU: luas area non-teks per blok (skala HH)
        self.text_variance_map = text_variance_map          # BARU: energi HH di area non-teks per blok
        self.metadata = metadata
        self.meta = metadata
        self.previous_hash = previous_hash
        self.tx_id = self.calculate_txid()
        self.hash = self.tx_id

    def calculate_txid(self):
        block_string = (f"{self.index}{self.timestamp}{json.dumps(self.grid_hashes)}"
                         f"{json.dumps(self.grid_colors)}{json.dumps(self.text_valid_pixels_map)}"
                         f"{json.dumps(self.text_variance_map)}{json.dumps(self.metadata)}{self.previous_hash}")
        return hashlib.sha256(block_string.encode()).hexdigest()

    def to_dict(self):
        return {
            "index": self.index, "timestamp": self.timestamp,
            "grid_hashes": self.grid_hashes, "grid_colors": self.grid_colors,
            "text_valid_pixels_map": self.text_valid_pixels_map,
            "text_variance_map": self.text_variance_map,
            "metadata": self.metadata,
            "previous_hash": self.previous_hash, "tx_id": self.tx_id, "hash": self.tx_id
        }

class SecureBlockchain:
    def __init__(self, db_file="opsi_ledger.json"):
        self.db_file = db_file
        self.chain = []
        self.bk_tree = BKTree()
        self.load_db()

    def save_db(self):
        temp_file = f"{self.db_file}.tmp"
        try:
            with open(temp_file, "w", encoding="utf-8") as f:
                json.dump([b.to_dict() for b in self.chain], f, indent=4)
                f.flush()
                os.fsync(f.fileno())
            os.replace(temp_file, self.db_file)
        except Exception as e:
            print(f"❌ Gagal menyimpan database JSON: {e}")

    def get_latest_block(self):
        return self.chain[-1]

    def check_duplicate(self, grid_hashes, threshold=0):
        new_flat_hash = "".join([str(h) for row in grid_hashes for h in row]) if isinstance(grid_hashes[0], list) else "".join(grid_hashes)
        for block in self.chain[1:]:
            if not hasattr(block, 'grid_hashes') or not block.grid_hashes:
                continue
            block_flat_hash = "".join([str(h) for row in block.grid_hashes for h in row]) if isinstance(block.grid_hashes[0], list) else "".join(block.grid_hashes)
            dist = calculate_hamming_distance(new_flat_hash, block_flat_hash)
            if dist <= threshold:
                return True, block
        return False, None

    def register_image(self, grid_hashes, metadata, grid_colors=None,
                        text_valid_pixels_map=None, text_variance_map=None):
        is_dup, existing_block = self.check_duplicate(grid_hashes, threshold=0)
        if is_dup:
            filename = existing_block.metadata.get("filename", "Unknown")
            print(f"  ⚠️ [DUPLIKAT DETECTED] Gambar sudah terdaftar di Block #{existing_block.index}")
            return None, existing_block

        latest = self.get_latest_block()
        new_block = Block(
            index=latest.index + 1, timestamp=time.time(),
            grid_hashes=grid_hashes, metadata=metadata, previous_hash=latest.tx_id,
            grid_colors=grid_colors,
            text_valid_pixels_map=text_valid_pixels_map, text_variance_map=text_variance_map
        )
        self.chain.append(new_block)
        self.bk_tree.insert((new_block.tx_id, new_block.grid_hashes, new_block.metadata, new_block))
        self.save_db()
        print(f"  ✅ [BLOCKCHAIN] Gambar BARU terdaftar! (Block #{new_block.index})")
        return new_block, None

    def load_db(self):
        if os.path.exists(self.db_file):
            try:
                with open(self.db_file, "r", encoding="utf-8") as f:
                    data = json.load(f)
                    self.chain = []
                    self.bk_tree = BKTree()
                    for item in data:
                        b = Block(
                            item["index"], item["timestamp"], item["grid_hashes"],
                            item["metadata"], item["previous_hash"],
                            grid_colors=item.get("grid_colors"),
                            text_valid_pixels_map=item.get("text_valid_pixels_map"),
                            text_variance_map=item.get("text_variance_map"),
                        )
                        b.tx_id = item.get("tx_id", item.get("hash"))
                        b.hash = b.tx_id
                        self.chain.append(b)
                        if b.index > 0:
                            self.bk_tree.insert((b.tx_id, b.grid_hashes, b.metadata, b))
                print(f"[+] Ledger JSON berhasil dimuat! ({len(self.chain)-1} citra asli terdaftar)")
            except (json.JSONDecodeError, Exception) as e:
                print(f"⚠️ [WARNING] File {self.db_file} rusak. Mereset Ledger...")
                self.create_genesis_block()
        else:
            self.create_genesis_block()

    def create_genesis_block(self):
        self.chain = []
        self.bk_tree = BKTree()
        genesis = Block(0, time.time(), [], {"filename": "Genesis Block OPSI"}, "0")
        self.chain.append(genesis)
        self.save_db()

print("[+] Cell 4 Siap — grid_colors + statistik HH text mask sekarang ikut disimpan & dimuat.")

import io
import glob
# -------------------------------------------------------------------------
# 1. PILIH SUMBER DATASET DI SINI: "gdrive" ATAU "kaggle"
# -------------------------------------------------------------------------
SOURCE_MODE = "kaggle"  # Ubah ke "gdrive" atau "kaggle" sesuai kebutuhan

# Parameter Google Drive (Dipakai jika SOURCE_MODE = "gdrive")
LINK_DRIVE = "https://drive.google.com/drive/folders/1g9xMtWxXNYx04P2POHLdm--NfM5Djllq"

# Parameter KaggleHub (Dipakai jika SOURCE_MODE = "kaggle")
KAGGLE_DATASET_SLUG = "paultimothymooney/chest-xray-pneumonia"
MAX_SAMPLING_KAGGLE = 100  # Batas jumlah gambar yang didaftarkan dari Kaggle

# -------------------------------------------------------------------------
# 2. PROSES UNDUH DATASET BERDASARKAN SUMBER YANG DIPILIH
# -------------------------------------------------------------------------
image_files = []

if SOURCE_MODE.lower() == "gdrive":
    print("[INFO] Menggunakan Sumber Data: Google Drive Online")
    from google.colab import drive, auth
    from google.auth import default
    from googleapiclient.discovery import build
    from googleapiclient.http import MediaIoBaseDownload

    auth.authenticate_user()
    creds, _ = default()
    drive_service = build('drive', 'v3', credentials=creds)

    folder_id = LINK_DRIVE.split("folders/")[1].split("?")[0]
    LOCAL_TEMP_DIR = '/content/dataset_opsi_online'
    os.makedirs(LOCAL_TEMP_DIR, exist_ok=True)

    print(f"[INFO] Membaca isi folder online dengan ID: {folder_id}")
    query = f"'{folder_id}' in parents and mimeType contains 'image/' and trashed = false"

    try:
        results = drive_service.files().list(q=query, fields="files(id, name)").execute()
        items = results.get('files', [])
    except Exception as e:
        query_alt = f"'{folder_id}' in parents and trashed = false"
        results = drive_service.files().list(q=query_alt, fields="files(id, name, mimeType)").execute()
        items = [f for f in results.get('files', []) if any(ext in f['name'].lower() for ext in ['.jpg', '.jpeg', '.png', '.webp'])]

    if not items:
        print("\n[!] ERROR: Tidak ada gambar terdeteksi di folder Google Drive tersebut.")
    else:
        print(f"[+] Menemukan {len(items)} gambar online. Mengunduh data ke runtime Colab...")
        for item in items:
            file_id = item['id']
            file_name = item['name']
            local_path = os.path.join(LOCAL_TEMP_DIR, file_name)

            request = drive_service.files().get_media(fileId=file_id)
            fh = io.FileIO(local_path, 'wb')
            downloader = MediaIoBaseDownload(fh, request)
            done = False
            while done is False:
                status, done = downloader.next_chunk()
            image_files.append(local_path)

elif SOURCE_MODE.lower() == "kaggle":
    print("[INFO] Menggunakan Sumber Data: KaggleHub API")
    import kagglehub

    print(f"[INFO] Mengunduh dataset dari Kaggle: {KAGGLE_DATASET_SLUG}...")
    try:
        dataset_path = kagglehub.dataset_download(KAGGLE_DATASET_SLUG)
        print(f"[+] Dataset berhasil diunduh di: {dataset_path}")

        # Cari file gambar di dalam folder Kaggle
        extensions = ('*.png', '*.jpg', '*.jpeg', '*.webp', '*.PNG', '*.JPG', '*.JPEG')
        for ext in extensions:
            image_files.extend(glob.glob(os.path.join(dataset_path, '**', ext), recursive=True))

        image_files = sorted(image_files)[:MAX_SAMPLING_KAGGLE]
    except Exception as e:
        print(f"❌ Gagal mengunduh dataset dari Kaggle: {e}")

else:
    print("❌ ERROR: Pilihan SOURCE_MODE tidak valid! Gunakan 'gdrive' atau 'kaggle'.")

# -------------------------------------------------------------------------
# 3. PROSES REGISTRASI BLOCKCHAIN & ANTI-DUPLIKASI
# -------------------------------------------------------------------------
if not image_files:
    print("\n[!] Registrasi dibatalkan karena tidak ada gambar yang siap diproses.")
else:
    image_files = sorted(image_files)
    print(f"[+] Berhasil sinkronisasi {len(image_files)} gambar. Memulai Registrasi Blockchain...\n")

    # Inisialisasi Blockchain dari CELL 4
    blockchain = SecureBlockchain()

    debug_logs = []
    total_asli = 0
    total_duplikat = 0
    total_gagal_baca = 0

    print("="*85)
    print(" PROGRES PENDAFTARAN BATCH BLOCKCHAIN (ANTI-DUPLIKASI) ")
    print("="*85)

    for idx, filepath in enumerate(image_files, start=1):
        filename = os.path.basename(filepath)

        img = cv2.imread(filepath)
        if img is None:
            total_gagal_baca += 1
            print(f"[{idx}/{len(image_files)}] {filename:<30} -> ❌ GAGAL BACA FILE")
            continue
   # Pra-pemrosesan Warna & Ekstraksi Grid Hashes (4x4)
        img_ycbcr = preprocess_image(img)
        grid_hashes, grid_colors = generate_grid_hashes(img_ycbcr, grid_size=4)

        text_mask = build_text_mask(img_ycbcr, canny_low=50, canny_high=150, dilate_size=3)
        inverse_mask = 1.0 - text_mask
        HH_matrix = compute_hh_subband(img_ycbcr)
        text_valid_pixels_map, text_variance_map = compute_masked_block_stats(
            HH_matrix, inverse_mask, grid_size=4, min_valid_fraction=0.1
        )

        h_asli, w_asli = img.shape[:2]
        blockiness_asli = measure_jpeg_blockiness(img, block_size=8)   # <- BARU, dari gambar MENTAH

        meta = {
            "filename": filename,
            "source": SOURCE_MODE,
            "status": "Registered Asli",
            "width": w_asli,             # <- BARU
            "height": h_asli,            # <- BARU
            "blockiness_score": blockiness_asli   # <- BARU
        }

        new_block, existing_block = blockchain.register_image(
            grid_hashes, meta,
            grid_colors=grid_colors,
            text_valid_pixels_map=text_valid_pixels_map,
            text_variance_map=text_variance_map
        )

      # Pendaftaran Ke Blockchain dengan Cek Duplikasi
        new_block, existing_block = blockchain.register_image(grid_hashes, meta, grid_colors=grid_colors)  # <- diubah

        block_index = None
        tx_id = None

        if new_block is not None:
            total_asli += 1
            block_index = new_block.index
            tx_id = new_block.tx_id
            print(f"[{idx}/{len(image_files)}] {filename:<30} -> ✅ TERDAFTAR (Block #{block_index} | TxID: {str(tx_id)[:10]}...)")
        else:
            total_duplikat += 1
            block_index = existing_block.index
            tx_id = existing_block.tx_id
            orig_file = existing_block.metadata.get("filename", "Unknown")
            print(f"[{idx}/{len(image_files)}] {filename:<30} -> ⚠️ DUPLIKAT! Sudah ada di Block #{block_index} (File Asli: {orig_file})")

        debug_logs.append({
            "no": idx,
            "filename": filename,
            "block_index": block_index,
            "tx_id": tx_id
        })

    # Rekapitulasi Akhir
    print("\n" + "="*85)
    print(" 📊 [REKAPITULASI HASIL REGISTRASI DATASET] ")
    print("="*85)
    print(f"Sumber Dataset                : {SOURCE_MODE.upper()}")
    print(f"Total Foto Diproses           : {len(image_files)} gambar")
    print(f"Total Foto Baru Terdaftar     : {total_asli} gambar")
    print(f"Total Foto Duplikat (Dilewati): {total_duplikat} gambar")
    if total_gagal_baca > 0:
        print(f"Total Gambar Corrupt/Gagal    : {total_gagal_baca} gambar")
    print(f"Total Blok dalam Blockchain   : {len(blockchain.chain)-1} blok")
    print("="*85)
    print("[INFO] Registrasi selesai! Silakan jalankan CELL 6 untuk verifikasi suspek.")



# =========================================================================
# CELL 6: VERIFIKASI SUSPEK (WARNA ABSOLUT + REJECTION THRESHOLD + TEKS via HH MASKED)
# =========================================================================
import os
import cv2
import glob
import numpy as np
import matplotlib.pyplot as plt
import time
import io

print("="*75)
print(" TAHAP 2: VERIFIKASI MEDIA SUSPEK (DYNAMIC DATASET SIZE) ")
print("="*75)

SOURCE_MODE = "gdrive"
MAX_SAMPLING_KAGGLE = 100
KAGGLE_SUSPECT_SLUG = "prasunroy/natural-images"
LINK_DRIVE_SUSPECT = "https://drive.google.com/drive/folders/1iZtpMg3WOWcsWeiB5Ve9l3RzJN_poBSq"
IMAGE_SIZE = (5, 5)

TOLERANSI_BRIGHT = 15.0
TOLERANSI_MID = 23.0
TOLERANSI_DARK = 27.0
TOLERANSI_BLOCKINESS = 1.5
TOLERANSI_WARNA_ABS = 6.0

MAX_MATCH_PERCENT = 35.0

# THRESHOLD DETEKSI TEKS (HH SUBBAND MASKED) - perlu dikalibrasi ke datasetmu
CANNY_LOW = 50
CANNY_HIGH = 150
DILATE_SIZE_TEXT = 3
MIN_VALID_FRACTION_TEXT = 0.1
TOLERANSI_TEKS_BARU = 0.15     # fraksi area blok (skala HH) yg berubah jadi "teks" -> dianggap teks baru
TOLERANSI_VARIANCE_HH = 50.0   # delta energi HH absolut di area non-teks -> sinyal sekunder (opsional)

active_blockchain = None
if 'blockchain' in globals() and hasattr(blockchain, 'chain') and len(blockchain.chain) > 1:
    active_blockchain = blockchain
    print(f"[+] Terhubung ke Blockchain di memori! ({len(blockchain.chain)-1} foto terdaftar)")
elif os.path.exists("opsi_ledger.json"):
    print("[INFO] Memuat ulang ledger blockchain dari opsi_ledger.json...")
    active_blockchain = SecureBlockchain("opsi_ledger.json")
    print(f"[+] Terhubung ke Ledger JSON! ({len(active_blockchain.chain)-1} foto terdaftar)")

if active_blockchain is None or len(active_blockchain.chain) <= 1:
    print("\n⚠️ [WARNING] Database Blockchain kosong/hanya berisi Genesis Block!")
    print("👉 Silakan jalankan CELL 5 terlebih dahulu untuk mendaftarkan dataset gambar asli.")
else:
    suspect_files = []

    if SOURCE_MODE.lower() == "kaggle":
        print("[INFO] Membaca Gambar Suspek dari: KaggleHub API")
        import kagglehub
        print(f"[INFO] Mengunduh dataset dari Kaggle: {KAGGLE_SUSPECT_SLUG}...")
        try:
            dataset_path = kagglehub.dataset_download(KAGGLE_SUSPECT_SLUG)
            extensions = ('*.png', '*.jpg', '*.jpeg', '*.webp', '*.PNG', '*.JPG', '*.JPEG')
            for ext in extensions:
                suspect_files.extend(glob.glob(os.path.join(dataset_path, '**', ext), recursive=True))
            suspect_files = sorted(suspect_files)
            total_ditemukan = len(suspect_files)
            if MAX_SAMPLING_KAGGLE is not None and MAX_SAMPLING_KAGGLE > 0:
                suspect_files = suspect_files[:MAX_SAMPLING_KAGGLE]
                print(f"[+] Total gambar di Kaggle: {total_ditemukan} | Diambil untuk pengujian: {len(suspect_files)} gambar.")
            else:
                print(f"[+] Mengambil SELURUH gambar dari dataset Kaggle: {total_ditemukan} gambar.")
        except Exception as e:
            print(f"❌ Gagal mengunduh dataset dari Kaggle: {e}")

    elif SOURCE_MODE.lower() == "gdrive":
        print("[INFO] Membaca Gambar Suspek dari: Google Drive Online (Termasuk Subfolder)")
        from google.colab import auth
        from google.auth import default
        from googleapiclient.discovery import build
        from googleapiclient.http import MediaIoBaseDownload

        auth.authenticate_user()
        creds, _ = default()
        drive_service = build('drive', 'v3', credentials=creds)

        folder_suspect_id = LINK_DRIVE_SUSPECT.split("folders/")[1].split("?")[0]
        LOCAL_SUSPECT_DIR = '/content/dataset_suspek_online'
        os.makedirs(LOCAL_SUSPECT_DIR, exist_ok=True)

        def get_all_images_in_drive(service, folder_id):
            all_images = []
            page_token = None
            while True:
                query_img = f"'{folder_id}' in parents and mimeType contains 'image/' and trashed = false"
                res_img = service.files().list(q=query_img, fields="nextPageToken, files(id, name)", pageToken=page_token).execute()
                all_images.extend(res_img.get('files', []))
                page_token = res_img.get('nextPageToken')
                if not page_token: break

            page_token = None
            while True:
                query_folder = f"'{folder_id}' in parents and mimeType = 'application/vnd.google-apps.folder' and trashed = false"
                res_folder = service.files().list(q=query_folder, fields="nextPageToken, files(id, name)", pageToken=page_token).execute()
                folders = res_folder.get('files', [])
                for folder in folders:
                    all_images.extend(get_all_images_in_drive(service, folder['id']))
                page_token = res_folder.get('nextPageToken')
                if not page_token: break
            return all_images

        try:
            items = get_all_images_in_drive(drive_service, folder_suspect_id)
        except Exception as e:
            print(f"[!] ERROR saat mencari file di GDrive: {e}")
            items = []

        if not items:
            print("\n[!] ERROR: Tidak ada gambar suspek ditemukan di folder Drive tersebut.")
        else:
            print(f"[+] Menemukan total {len(items)} gambar suspek. Mengunduh data...")
            for item in items:
                file_id = item['id']
                file_name = item['name']
                safe_file_name = f"{file_id}_{file_name}"
                local_path = os.path.join(LOCAL_SUSPECT_DIR, safe_file_name)
                if not os.path.exists(local_path):
                    request = drive_service.files().get_media(fileId=file_id)
                    fh = io.FileIO(local_path, 'wb')
                    downloader = MediaIoBaseDownload(fh, request)
                    done = False
                    while done is False:
                        status, done = downloader.next_chunk()
                suspect_files.append(local_path)

    if not suspect_files:
        print("\n[!] Pengujian dibatalkan karena tidak ada gambar suspek.")
    else:
        total_diuji = len(suspect_files)
        total_real = 0
        total_fake = 0
        total_unknown = 0
        TOTAL_BITS_STRUKTUR = 16 * 512

        print(f"[+] Memulai Analisis Forensik untuk {total_diuji} gambar...\n")

        for idx, filepath in enumerate(suspect_files, start=1):
            filename_suspect = os.path.basename(filepath)
            img_suspect = cv2.imread(filepath)
            blockiness_suspect = measure_jpeg_blockiness(img_suspect, block_size=8)
            if img_suspect is None:
                print(f"[{idx}/{total_diuji}] {filename_suspect:<30} -> ❌ GAGAL BACA FILE")
                continue

            h_orig, w_orig = img_suspect.shape[:2]
            if max(h_orig, w_orig) > 1024:
                scale = 1024.0 / max(h_orig, w_orig)
                img_suspect_fast = cv2.resize(img_suspect, (int(w_orig * scale), int(h_orig * scale)), interpolation=cv2.INTER_AREA)
            else:
                img_suspect_fast = img_suspect

            img_suspect_ycbcr = preprocess_image(img_suspect_fast)
            hash_suspect, color_suspect = generate_grid_hashes(img_suspect_ycbcr, grid_size=4)

            text_mask_suspect = build_text_mask(img_suspect_ycbcr, canny_low=CANNY_LOW, canny_high=CANNY_HIGH, dilate_size=DILATE_SIZE_TEXT)
            inverse_mask_suspect = 1.0 - text_mask_suspect
            HH_suspect = compute_hh_subband(img_suspect_ycbcr)
            valid_pixels_suspect, variance_suspect = compute_masked_block_stats(
                HH_suspect, inverse_mask_suspect, grid_size=4, min_valid_fraction=MIN_VALID_FRACTION_TEXT
            )
            total_pixel_blok_hh = (HH_suspect.shape[0] // 4) * (HH_suspect.shape[1] // 4)

            best_match_block = None
            min_total_hd = float('inf')
            for block in active_blockchain.chain[1:]:
                block_grid_hashes = getattr(block, 'grid_hashes', None)
                if not block_grid_hashes: continue
                total_hd = 0
                for i in range(4):
                    for j in range(4):
                        total_hd += calculate_hamming_distance(block_grid_hashes[i][j], hash_suspect[i][j])
                if total_hd < min_total_hd:
                    min_total_hd = total_hd
                    best_match_block = block

            if best_match_block is None:
                print(f"[{idx}/{total_diuji}] {filename_suspect:<30} -> ❌ TIDAK COCOK DENGAN BLOCKCHAIN")
                continue

            persen_gap_match = (min_total_hd / TOTAL_BITS_STRUKTUR) * 100
            if persen_gap_match > MAX_MATCH_PERCENT:
                total_unknown += 1
                print(f"[{idx}/{total_diuji}] {filename_suspect:<30} -> ❓ TIDAK DIKENALI (gap {persen_gap_match:.1f}%) \n")
                continue

            hash_asli = best_match_block.grid_hashes
            color_asli = getattr(best_match_block, 'grid_colors', None)
            valid_pixels_asli = getattr(best_match_block, 'text_valid_pixels_map', None)
            variance_asli = getattr(best_match_block, 'text_variance_map', None)
            meta_data = getattr(best_match_block, 'metadata', getattr(best_match_block, 'meta', {}))
            w_asli = meta_data.get('width')
            h_asli = meta_data.get('height')
            blockiness_asli = meta_data.get('blockiness_score')

            resolusi_berubah = (w_asli is not None and (w_orig != w_asli or h_orig != h_asli))

            kompresi_bertambah = False
            delta_blockiness = 0.0
            if blockiness_asli is not None:
                delta_blockiness = blockiness_suspect - blockiness_asli
                kompresi_bertambah = delta_blockiness > TOLERANSI_BLOCKINESS
            matched_filename = meta_data.get("filename", "Unknown")

            grid_size = 4
            y_channel = img_suspect_ycbcr[:, :, 0]
            step_h, step_w = img_suspect_ycbcr.shape[0] // grid_size, img_suspect_ycbcr.shape[1] // grid_size

            tamper_map = np.zeros((grid_size, grid_size))
            text_flag_map = np.zeros((grid_size, grid_size))
            is_tampered = False

            for i in range(grid_size):
                for j in range(grid_size):
                    patch_y = y_channel[i*step_h:(i+1)*step_h, j*step_w:(j+1)*step_w]
                    mean_brightness = np.mean(patch_y)
                    thresh_str = TOLERANSI_DARK if mean_brightness < 45.0 else (TOLERANSI_MID if mean_brightness < 80.0 else TOLERANSI_BRIGHT)

                    hd_struktur = calculate_hamming_distance(hash_asli[i][j], hash_suspect[i][j])
                    struktur_berubah = (hd_struktur / 512.0) * 100 > thresh_str

                    warna_berubah = False
                    if color_asli is not None:
                        c_asli = color_asli[i][j]
                        c_suspect = color_suspect[i][j]
                        delta_warna = max(abs(a - b) for a, b in zip(c_asli, c_suspect))
                        warna_berubah = delta_warna > TOLERANSI_WARNA_ABS

                    if struktur_berubah or warna_berubah:
                        tamper_map[i, j] = 1
                        is_tampered = True

                    # --- CEK TEKS: HH subband masked, delta vs ASLI ---
                    teks_berubah_blok = False
                    if valid_pixels_asli is not None:
                        vp_asli = valid_pixels_asli[i][j]
                        vp_suspect = valid_pixels_suspect[i][j]
                        penyusutan_area_bersih = (vp_asli - vp_suspect) / total_pixel_blok_hh
                        if penyusutan_area_bersih > TOLERANSI_TEKS_BARU:
                            teks_berubah_blok = True

                        if variance_asli is not None:
                            var_asli = variance_asli[i][j]
                            var_suspect = variance_suspect[i][j]
                            if var_asli >= 0 and var_suspect >= 0:
                                if abs(var_asli - var_suspect) > TOLERANSI_VARIANCE_HH:
                                    teks_berubah_blok = True

                    if teks_berubah_blok:
                        tamper_map[i, j] = 1
                        text_flag_map[i, j] = 1
                        is_tampered = True

            # Apply general tamper flags based on resolution and blockiness *before* printing the first status
            if resolusi_berubah or kompresi_bertambah:
                is_tampered = True

            status_text = "❌ FAKE (DIMANIPULASI)" if is_tampered else "✅ REAL (AUTENTIK)"
            if is_tampered: total_fake += 1
            else: total_real += 1

            info_tambahan = ""
            if np.any(text_flag_map == 1):
                info_tambahan += " [+ teks]"
            if resolusi_berubah:
                info_tambahan += f" [+ resolusi: asli {w_asli}x{h_asli} vs suspek {w_orig}x{h_orig}]"
            if kompresi_bertambah:
                info_tambahan += f" [+ kompresi naik, Δblockiness={delta_blockiness:.2f}]"

            print(f"[{idx}/{total_diuji}] {filename_suspect:<30} -> {status_text}{info_tambahan}")

            # Visualisasi: SEMUA blok tamper (struktur/warna/teks) sekarang MERAH POLOS, tanpa oranye
            img_rgb = cv2.cvtColor(img_suspect_ycbcr, cv2.COLOR_YCrCb2RGB)
            overlay = img_rgb.copy()
            for i in range(grid_size):
                for j in range(grid_size):
                    if tamper_map[i, j] == 1:
                        cv2.rectangle(overlay, (j*step_w, i*step_h), ((j+1)*step_w, (i+1)*step_h), (255, 0, 0), -1)
                    cv2.rectangle(img_rgb, (j*step_w, i*step_h), ((j+1)*step_w, (i+1)*step_h), (255, 255, 255), 1)
            blended = cv2.addWeighted(overlay, 0.45, img_rgb, 0.55, 0)
            plt.figure(figsize=IMAGE_SIZE)
            plt.imshow(blended)
            plt.axis('off')
            plt.show()

        print("\n" + "="*75)
        print(" 📊 [REKAPITULASI HASIL] ")
        print("="*75)
        print(f"Total Diuji: {total_diuji} | REAL: {total_real} | FAKE: {total_fake} | UNKNOWN: {total_unknown}")